[package]
name = "rliterate_core"
version = "0.1.0"
authors = ["Isaac van Bakel <ivb@vanbakel.io>"]

[dependencies]
log = "0.4"
peg = "0.8"
bitflags = "^1.0"
subprocess = "0.1"

pulldown-cmark = "0.1"
prettify-cmark = "0.1"
maud = "0.25"

